name = "OpticalPropagation"
uuid = "bd2a9720-0cf4-11ea-3d1a-97ce67aae37d"
authors = ["miRoox"]
version = "0.2.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
FFTW = "1"
RecipesBase = "1"
Unitful = "1"
julia = "1.4"
